[package]
name = "mosaic"
version = "0.1.0"
authors = ["verdie-g <gregoire.verdier@gmail.com>"]
edition = "2018"

[dependencies]
image = "^0.21.0"
num = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
walkdir = "2"
clap = "2.33.0"
